# Generated by Django 6.0.4 on 2026-06-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('QR', 'Código QR (Nequi/Daviplata/Bancolombia)'), ('TR', 'Transferencia Directa'), ('TD', 'Tarjeta')], default='EF', max_length=2),
        ),
    ]
